os:
  - osx

# OS X Qt http://braumeister.org/search/qt5
# we need to use macdeployqtfix after using macdeployqt to fix the library paths!
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install qt5
      export QTDIR="/usr/local/opt/qt5"
    fi

script:
  - cd src
  - source /opt/qt55/bin/qt55-env.sh
  - cd external
  - qmake --version
  - qmake 
  - make 