# Enable C++ support
language: cpp

os:
  - osx

install:
  - cd ..
  - git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git
  - cd meshlab
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install qt5
      export QTDIR="/usr/local/opt/qt5"
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="$QTDIR/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then LDFLAGS=-L$QTDIR/lib             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then CPPFLAGS=-I$QTDIR/include        ;fi
  - cd src
  - cd external
  - qmake 
  - make
  - cd ..
  - qmake meshlab_full.pro
  - make 
