# Enable C++ support
language: cpp

os:
  - osx

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install llvm
      export PATH="/usr/local/opt/llvm/bin:$PATH"
      which clang
      clang++-mp-3.9 --version
      clang --version
      brew install qt5      
      export QTDIR="/usr/local/opt/qt5"
    fi
  - cd ..
  - git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git
  - cd meshlab

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="/usr/local/opt/llvm/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ls /usr/local/opt/llvm            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ls /usr/local/opt/llvm/lib           ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ls  /usr/local/opt/llvm/bin            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then which clang             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ln -s /usr/local/opt/llvm/bin/clang /usr/local/opt/llvm/bin/clang++-mp-3.9       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="$QTDIR/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then LDFLAGS=-L$QTDIR/lib            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then CPPFLAGS=-I$QTDIR/include        ;fi
  - cd src
  - cd external
  - qmake 
  - make
  - cd ..
  - qmake "QMAKE_LFLAGS+=-L/usr/local/opt/llvm/lib -lomp" meshlab_mini.pro 
  - make 
