branches:
  only:
    - master

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\vcglib
# Build Configuration, i.e. Debug, Release, etc.
configuration:
#  - release
  - debug
  
environment:
  matrix:
    # Microsoft Visual Studio 64bit
    - QTDIR: C:\Qt\5.10.0\msvc2015
      VSVER: 14.0
      SPEC: win32-msvc2015
      COMPILER: nmake
      #ARTIFACT: $(APPVEYOR_PROJECT_NAME)-%APPVEYOR_REPO_TAG_NAME%.%APPVEYOR_BUILD_NUMBER%-win64.zip
      #ARTIFACT: $(APPVEYOR_PROJECT_NAME)-%APPVEYOR_REPO_TAG_NAME%-win64.zip



# Set paths, etc.
before_build:
  # Set paths
  #- '%QTDIR%\bin\qtenv2.bat'
  - call "%QTDIR%\bin\qtenv2.bat"
  # Show qmake and make version
  - qmake -v
  # Detect architecture (32bit or 64bit)
  - if %QTDIR:_64=%==%QTDIR% (set ARCH=x86) else (set ARCH=x64)
  # Set more... if Microsoft Visual Studio
  - if %COMPILER%==nmake call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  # Show build folder
  - echo %APPVEYOR_BUILD_FOLDER%
  - echo %CONFIGURATION%
  - dir
  
# To run your custom scripts instead of automatic MSBuild
build_script:
  # Go to clone directory
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd src
  # Run qmake
  - qmake meshlab_mini.pro -r -spec %SPEC% "CONFIG+=%CONFIGURATION%"
  # Run compiler
  #- '%COMPILER%'
  - call %COMPILER%
